lesson_5/todo/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :events
  get 'about', to: 'about#index', as: 'about_index'
  get 'about/:hello', to: 'about#index', additional: 'true'
  root 'events#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

lesson_5/todo/app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

lesson_5/todo/app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :commentable, polymorphic: true

  # after_touch :log_comment

  # private

  # def log_comment
  #   Rails.logger.info '########################################'
  #   Rails.logger.info updated_at
  #   Rails.logger.info '########################################'
  # end
end

lesson_5/todo/app/models/event.rb
# frozen_string_literal: true

class Event < ApplicationRecord
  validates :name, presence: true
  validates :user_id, presence: true

  belongs_to :user, -> { where(active: true) }, counter_cache: true
  has_many :items, dependent: :destroy
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :commentators, through: :comments, source: :user
end

lesson_5/todo/app/models/item.rb
# frozen_string_literal: true

class Item < ApplicationRecord
  validates :name, presence: true
  validates :name, uniqueness: true
  validates :event_id, presence: true

  belongs_to :event
end

lesson_5/todo/app/models/role.rb
# frozen_string_literal: true

class Role < ApplicationRecord
  validates :name, presence: true
  validates :name, uniqueness: true
  validates :code, presence: true
  validates :code, uniqueness: true

  has_many :users
end

lesson_5/todo/app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  before_validation :normalize_email, if: proc { |u| u.email.present? }

  private

  def normalize_email
    self.mail = email.downcase
  end

  validates :name, presence: true
  validates :name, length: { maximum: 16, minimum: 2 }
  validates :name, uniqueness: true

  scope :default, -> { where(role_id: Role.find_by(code: :default).id) }
  scope :fresh, ->(created_at) { where('created_at > ?', created_at) }
  scope :default_fresh, ->(created_at) { default.fresh(created_at) }

  store :settings, coder: JSON
  store_accessor :settings, :per_page, :time_zone, :show_help

  enum state: {
    created: 1,
    email_verified: 2,
    studied: 3,
    actived: 4,
    disabled: 5
  }

  belongs_to :role
  has_many :events, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :commented_events,
           through: :comments,
           source: :commentable,
           source_type: :Event
  has_many :commented_users,
           through: :comments,
           source: :commentable,
           source_type: :User
end

lesson_5/todo/app/controllers/about_controller.rb
# frozen_string_literal: true

class AboutController < ApplicationController
  def index; end

  def help; end
end

lesson_5/todo/app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

lesson_5/todo/app/controllers/events_controller.rb
# frozen_string_literal: true

class EventsController < ApplicationController
  before_action :set_event, only: %i[show edit update destroy]

  # GET /events or /events.json
  def index
    @events = Event.includes(:items).page(params[:page]).per(3)
  end

  # GET /events/1 or /events/1.json
  def show; end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit; end

  # POST /events or /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to event_url(@event), notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to event_url(@event), notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def event_params
    params.require(:event).permit(:name, :content, :done)
  end
end

lesson_5/todo/app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

lesson_5/todo/app/views/about/help.html.erb
<h1 class="main_header">Помощь</h1>
<p>
	<%= link_to 'О нас', about_path %>
	<%= link_to 'Главная страница', root_path %>
</p>

<p>Данный раздел находится в разработке, так как функционал приложения не реализован.</p>

lesson_5/todo/app/views/about/index.html.erb
<h1 class="main_header">О нас</h1>
<p>
	<%= link_to 'Главная страница', root_path %>
	<%= link_to 'Помощь', help_path %>
</p>

<h1 class="main_header">TODO-приложение для ведения списка дел.</h1>
<p>Приложение позволяет:</p>
<ul class="list">
	<li>Cоздавать запись о&nbsp;деле, предоставляя возможность задать 
	 название, описание и&nbsp;дату предстоящего дела;</li>

	<li>Редактировать уже созданные ранее дела (исправлять ошибки, 
			корректировать дату); </li>

	<li>Удалять дела, созданные по&nbsp;ошибке;</li>

	<li>Отмечать дело как выполненное</li>
</ul>

lesson_5/todo/app/views/events/_form.html.erb
<%= form_with(model: event) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :done %>
    <%= form.check_box :done %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

lesson_5/todo/app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

lesson_5/todo/app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Events</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.items.size %></td>
        <td><%= link_to event.name.truncate(80), event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>
<br>
<br>
<%= paginate @events %> 

lesson_5/todo/app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

lesson_5/todo/app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p> <strong> Name: <%= @event.name %> </strong> </p>

<p> <strong> Content: <%= @event.content %> </strong> </p>

<p> <strong> Done: <%= @event.done %> </strong> </p>

<p>
	<strong>Items: </strong>
	<table>
		<% @event.items.order(:created_at).each_with_index do |item, i| %>
			   <tr> 

			     <td> <%= i + 1 %> </td>
			     <td> <%= item.name %> </td>

			   </tr>
			<% end %>
	</table>
</p>


<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

lesson_5/todo/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>